### ISSUE TITLE
Getting filtered transactions

### ISSUE THREAD

**Issue by matiasosuna** [y-pakorn/flutter_web3#11]
Is there an example on how to get transactions by a specific filter?

I.E. Getting all transactions made to a specific contract

**Comment by y-pakorn** [comment]
By using `getLogs` on `Provider` or `queryFilter` on `Contract`.

There's already an example on both Ethers documentation and this package readme.

- https://docs.ethers.io/v5/api/providers/provider/#Provider-getLogs
- https://docs.ethers.io/v5/api/contract/contract/#Contract-queryFilter
- https://github.com/y-pakorn/flutter_web3#contract

**Comment by matiasosuna** [comment]
I've used both getLogs on Provider and queryFilter on Contract (like you did in the readme). Maybe you can tell me what I'm doing wrong:

I'm currently using the BSC Testing Network and when I use provider!.getLogs() with a Transfer event topic I do get a list of Logs but none of them belong to my address (and I've made at least 10).

```dart
final topics = ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"];
final logsList = await provider!.getLogs(Filter(topics: topics));
print('getLogs: $logsList');
logsList.forEach((element) {
        print('address: ${element.address}\ndata: ${element.data}\n');
      });
```

Using the queryFilter method on Contract I get an empty list. 

```dart
final abi = [
        "function name() view returns (string)",
        "function symbol() view returns (string)",
        "function balanceOf(address) view returns (uint)",
        "function transfer(address to, uint amount)",
        "event Transfer(address indexed from, address indexed to, uint amount)"
];
final busd = Contract(address, Interface(abi), provider!.getSigner());
print('Address: ${busd.address}');
final filter = busd.getFilter('Transfer');
print(filter.address);
print(filter.topics);
final events = await busd.queryFilter(filter, -100);
print('Transfer events: $events');
```

Do you know how I can get the list of transactions made with my address? (I know that to filter my address I have to include it in the topics but I get an empty list of Logs if I do that). 

Thanks in advance!

**Comment by y-pakorn** [comment]
You must include the filter topic constraint. The constraint put in can be determined by the event abi.

Such as this filter will yield.
```dart
final filter = busd.getFilter('Transfer', [currentAddress]);
// Filter: 0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee with [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef, 0xsomeAddressHere] from null to null
```

To elaborate, your `Transfer` event abi is `event Transfer(address indexed from, address indexed to, uint amount)` 
Then you can put `from`, `to`, and `amount` constraint into the filter.
`getFilter('Transfer', [currentAddress])` means you ask for `Transfer` filter that `from` is `currentAddress` and to `null` with `null` amount, `null` here translate to **any**. So it's `Transfer` event that's sent from your account.

```dart
final res = await busd.queryFilter(filter);
// [Event: Transfer Transfer(address,address,uint256) with args [0xsomeAddressHere, 0x000000000000000000000000000000000000dEaD, 1000000]]
// Transfer event that sent from 0xsomeAddressHere to dead address with amount of 1000000
```

**Comment by y-pakorn** [comment]
Noted that `Binance Smart Chain` can only pull logs [within 5k block.](https://docs.binance.org/smart-chain/developer/rpc.html) (This only applies to `Mainnet`.)
