### ISSUE TITLE
How to interact with a payable method in a contract?

### ISSUE THREAD

**Issue by mlemos** [y-pakorn/flutter_web3#12]
I'm trying to interact with a payable function/method in a contract.
But I'm not sure on how to specify the value on the code and I'm getting this error:

<img width="704" alt="Screen Shot 2021-09-25 at 12 51 57 PM" src="https://user-images.githubusercontent.com/29751/134777636-112e98a3-27c4-4008-a50e-f72a3fce764e.png">

Basically I don't know how to define the value in a payable transaction with a contract.

My ABI is like this:

`
"function bet(uint256[] max) payable returns (bool)"
`

And I'm calling the like this:

```
if (contract == null) {
  contract = Contract(
    address,
    Interface(abi),
    provider!.getSigner(),
  );
}
final tx = await contract.send(
  'bet',
  [max],
);
```

Any help is welcome!

**Comment by y-pakorn** [comment]
Define `override` property in `send` method to be not null.

Example.
```dart
final tx = await contract.send(
  'somePaybleFunction',
  [],
  TransactionOverride(value: BigInt.from(1)),
);
```
