### ISSUE TITLE
Add revert reason to transaction receipt status

### ISSUE THREAD

**Issue by jpiabrantes** [y-pakorn/flutter_web3#18]
Currently the transaction receipt gives a non-informative String

When the transaction is reverted.
```dart
  @override
  String toString() => status
      ? 'TransactionReceipt: ${transactionHash.substring(0, 10)} from ${from.substring(0, 10)} with $confirmations confirmations and ${logs.length} logs'
      : 'TransactionReceipt: ${transactionHash.substring(0, 10)} reverted ';
```

It would be great to add the revert reason.

**Comment by y-pakorn** [comment]
Not possible out of the box. Unparsed `TransactionReceipt` object did not contain the revert reason string.

Maybe you should ask Ethers Github/community.

**Comment by jpiabrantes** [comment]
> Not possible out of the box. Unparsed `TransactionReceipt` object did not contain the revert reason string.
> Maybe you should ask Ethers Github/community.

Really? How do other websites inform people about the error? What do they use?

**Comment by y-pakorn** [comment]
https://github.com/ethers-io/ethers.js/issues/368
