### ISSUE TITLE
Is there a way to send tokens to the signer by getting the token from an contract address?

### ISSUE THREAD

**Issue by URSFR** [y-pakorn/flutter_web3#36]
I've been looking in the documentation, but I haven't found (At least not in the way I've understood the docs) any way to send tokens to the signer (for example, through a contract signed by the signer, the contract address token sends the tokens).
Is there a way to have it natively provided by the SDK?

In such a case that it does not exist, is it safe to make an endpoint in which the contract token address is given and the tokens are delivered from there?

Another way could be creating the wallet in the application and somehow refer to the created address and send the tokens via Contract.send?

**Comment by y-pakorn** [comment]
Can you elaborate on what you are trying to do? what did you mean on 

> send tokens to the signer
> through a contract signed by the signer, the contract address token sends the tokens

Smart contract owned address is not the same as EOA.

**Comment by URSFR** [comment]
I mean that an EOA (Wallet A) through a smart contract signed by the signer (Wallet B) sends tokens to the signer when the contract is signed, these tokens should be sent automatically to the signer

**Comment by y-pakorn** [comment]
Smart contract address only performs as a smart contract, not as an EOA.
So smart contracts can't be used to perform any transaction signing. what did you mean 

> smart contract signed by the signer Wallet B

You can send ethers along when calling a function using `payable` method. and then if you want to send it further to the deployer or someone else you can program the contract to do that.
