### ISSUE TITLE
Signing Hashed Message and using verifyMessage returns incorrect address

### ISSUE THREAD

**Issue by evotianusx** [y-pakorn/flutter_web3#40]
**Describe the bug**
I tried to sign using the `txReceipt = await web3wc!.getSigner().signMessage( EthUtils.hashMessage("TEST"))` which properly prompt the wallet to sign the transaction. Using the return hash, I then call the `EthUtils.verifyMessage("TEST", txReceipt)`. The resulting address is not the same as the one used when signing the message

**Expected behavior**
Same address that sign the message should be the return value of `EthUtils.verifyMessage("TEST", txReceipt)`

**Additional context**
I used the walletConnect Provider and running on Binance Chain (ID 56)

**Comment by y-pakorn** [comment]
Wrong usage. Please refer to [ethers documentation](https://docs.ethers.io/v5/api/signer/#Signer-signMessage).

```dart
final address = await web3wc!.getSigner().getAddress();
final signature = await web3wc!.getSigner().signMessage("Hello");
final decodedAddress = EthUtils.verifyMessage("Hello", signature);
print(address == decodedAddress); // true

final address2 = await web3wc!.getSigner().getAddress();
final signature2 =
    await web3wc!.getSigner().signMessage(EthUtils.hashMessage("Hello"));
final decodedAddress2 =
    EthUtils.verifyMessage(EthUtils.hashMessage("Hello"), signature2);
print(address2 == decodedAddress2); // true
```
