### ISSUE TITLE
How can a transaction be performed without metamask?

### ISSUE THREAD

**Issue by dvalevv** [y-pakorn/flutter_web3#42]
Hello, I am trying to execute transaction using the private wallet key instead of Metamask.

Simply my question is: 
- How to execute transaction from Contract(address, abi), which is not signed by Metamask provider, but programmatically using a wallet's private key, where the gas parameters can also be set programmatically. The aim is to completely remove the visual interaction with the browser's extension for faster execution.
- or how can you execute transaction from Contract(address, abi, provider) specifying your own gas parameters?

**Comment by dvalevv** [comment]
I am closing the issue as after long search in the documentation I found that it can be done using TransactionOverride.

**Comment by princepspolycap** [comment]
@dvalevv Do you know how to get the balance of an account on something like the Gnosis Chain ? I keep getting the error that my provider is undefined or null, I created an issue here explaining more information https://github.com/y-pakorn/flutter_web3/issues/43

**Comment by dvalevv** [comment]
Usually it must work like this:

### 1. First: don't forget to add these into your flutter_app/web/index.html inside the head tag

```
<script src="https://cdn.ethers.io/lib/ethers-5.4.umd.min.js" type="application/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/@walletconnect/web3-provider@1.6.5/dist/umd/index.min.js" type="application/javascript"></script>
```

### 2. Then:

For native token:

```
final rpcProvider = JsonRpcProvider('https://rpc.gnosischain.com/');
var balance = await rpcProvider.getBalance("your_wallet_address");
```

For ERC20 token you can:
- either create ```Contract(address, abi, provider)``` and then ```await contract.call<BigInt>("balanceOf", ["wallet_address"])```
- or create ```ContractERC20(address, provider)``` and ```await contract.balanceOf("wallet_address")```

----
If you give me more info I can try it and send you the working code.
