### ISSUE TITLE
WalletConnect by mobile linking is failed connect to wallet

### ISSUE THREAD

**Issue by Tepehan** [y-pakorn/flutter_web3#48]
WalletConnect by mobile linking is failed to connect the wallet.

İf try to connect the trust wallet via WC on deep linking  is  failed.
(There is no issue with QR connection. )

**Comment by Tepehan** [comment]
I have found the reason of issue that is "http" protocol.The website is published as http path. I have replaced the "https" instead of  "http".So it's all right now.

**Comment by 4xMafole** [comment]
Hello, @Tepehan would you mind closing the issue?
