### ISSUE TITLE
Internal JSON-RPC error. When I called the contract.sned(), I couldn't even get my metamask plugin to show up but got this error

### ISSUE THREAD

**Issue by ringockmg** [y-pakorn/flutter_web3#5]
![Screen Shot 2021-08-08 at 9 09 29 PM](https://user-images.githubusercontent.com/77355681/128633121-58418a9e-3eca-4d21-8ed0-0d16bf79e60e.png)

{code: -32603, message: "Internal JSON-RPC error.", data: {…}}code: -32603data: code: -32000message: "execution reverted"Symbol(dartx.hashCode): undefinedSymbol(dartx.runtimeType): (...)[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()Symbol(dartx._equals): ƒ _equals(other)Symbol(dartx.hashCode): (...)Symbol(dartx.noSuchMethod): ƒ noSuchMethod(invocation)Symbol(dartx.runtimeType): (...)Symbol(dartx.toString): ƒ ()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get Symbol(dartx.hashCode): ƒ hashCode()get Symbol(dartx.runtimeType): ƒ runtimeType()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()message: "Internal JSON-RPC error."Symbol(dartx.hashCode): (...)Symbol(dartx.runtimeType): undefined[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()Symbol(dartx._equals): ƒ _equals(other)Symbol(dartx.hashCode): (...)Symbol(dartx.noSuchMethod): ƒ noSuchMethod(invocation)Symbol(dartx.runtimeType): (...)Symbol(dartx.toString): ƒ ()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get Symbol(dartx.hashCode): ƒ hashCode()get Symbol(dartx.runtimeType): ƒ runtimeType()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

**Comment by y-pakorn** [comment]
This is not related to the package.

`execution reverted` means an error on the EVM side. Please check your Solidity source code that met `revert` or `assert`.

**Comment by ringockmg** [comment]
Sorry for asking stupid question, may I know how if I can call a payable function with input using this library? I reckon maybe that's what causing the error. In my code written in web3, I used this:

this.contract.function(input, {'from': sender, 'to': receiver, 'value': web3.toWei(deposit, 'ether')},
