### ISSUE TITLE
After upgrade v1.0.20 to v2.0.4 , cannot connect to the contract.

### ISSUE THREAD

**Issue by ZhangBrian** [y-pakorn/flutter_web3#8]
i can get the signer from provider.getSigner(), and it can be used connect to contract.But after upgrade to v2.0.4, cannot connect to contract. receive a error:{reason: invalid signer or provider, code: INVALID_ARGUMENT, argument: signerOrProvider, value: {}}.

```
final provider = Web3Provider(ethereum!);
final signer = provider.getSigner();

_vaultContract!.connect(signer);  // Error
```

**Comment by y-pakorn** [comment]
Will be fixed in v2.0.5. Meanwhile, you can initiate the contract with the signer to bypass this problem.

**Comment by y-pakorn** [comment]
Package version 2.0.5 has been published, please update to avoid the problem. Closing now.

**Comment by ZhangBrian** [comment]
That‘s great！
